/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GestorTienda;

import java.sql.*;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.JTable.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
/**
 *
 * @author jacob
 */
public class VistaUsuario extends javax.swing.JFrame {
    
    /**
     * Creates new form VistaUsuario
     * @param email
     */
    public VistaUsuario(String email) {
        initComponents();
        CustomId.setText(email);
    }

    public static Cliente user;
    
    private static final String USERNAME = "rootx";
    private static final String PASSWORD = "rootx";
    private static final String CONN_STRING = "jdbc:mysql://localhost:3306/gestor_tienda?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC";

    private VistaUsuario() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comprar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        compu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tv = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        Dinero = new javax.swing.JLabel();
        saldo = new javax.swing.JTextField();
        CustomId = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        priceConf = new javax.swing.JTextField();
        confirm = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        info = new javax.swing.JButton();
        info1 = new javax.swing.JTextField();
        info2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Area = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comprar.setText("Buy");
        comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 51));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        compu.setText("Ver");
        compu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compuActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Comprar");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Ver Compus Disponibles");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Ver TVs Disponibles");

        tv.setText("Ver");
        tv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Ver Telefonos Disponibles");

        tel.setText("Ver");
        tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telActionPerformed(evt);
            }
        });

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Marca", "Precio", "Info", "Info"
            }
        ));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setText("¡Bienvenido!");

        Dinero.setText("Saldo:");

        saldo.setEditable(false);
        saldo.setBackground(new java.awt.Color(255, 255, 255));
        saldo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        saldo.setForeground(new java.awt.Color(0, 0, 0));
        saldo.setText("Actualizar");
        saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoActionPerformed(evt);
            }
        });

        CustomId.setText("User");

        jLabel8.setText("(Haga click en el item )");

        jLabel10.setText("Precio: ");

        priceConf.setBackground(new java.awt.Color(255, 255, 255));
        priceConf.setForeground(new java.awt.Color(0, 0, 0));

        confirm.setBackground(new java.awt.Color(0, 0, 0));
        confirm.setForeground(new java.awt.Color(255, 255, 255));
        confirm.setText("Confirmar");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11.setText("Actualizar Saldo");

        jButton3.setText("Ver");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("Ver Info de Producto");

        info.setText("Ver");
        info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoActionPerformed(evt);
            }
        });

        info1.setBackground(new java.awt.Color(0, 0, 0));
        info1.setForeground(new java.awt.Color(255, 255, 255));

        info2.setBackground(new java.awt.Color(0, 0, 0));
        info2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Nombre");

        jLabel9.setText("Marca");

        Area.setBackground(new java.awt.Color(0, 0, 0));
        Area.setColumns(20);
        Area.setForeground(new java.awt.Color(255, 255, 255));
        Area.setRows(5);
        jScrollPane2.setViewportView(Area);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(Dinero)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(42, 42, 42)
                                                .addComponent(tv))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(41, 41, 41)
                                                    .addComponent(tel)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(confirm)
                                            .addComponent(priceConf, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(comprar)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(jButton3))
                                            .addComponent(jLabel11)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addComponent(jLabel1))
                                            .addComponent(jLabel8)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(compu)))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6))
                        .addGap(10, 10, 10)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(CustomId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(info1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(info2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(info)))
                .addGap(74, 74, 74)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Dinero)
                            .addComponent(saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CustomId))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(compu)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(tel)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(priceConf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(confirm)
                        .addGap(18, 18, 18)
                        .addComponent(comprar)
                        .addGap(75, 75, 75))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(info1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(info2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(info)
                        .addGap(53, 53, 53))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        Welcome well = new Welcome();
        well.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void compuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compuActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)Tabla.getModel();
        try {
            int i = 0;
            int rows = Tabla.getRowCount();
            while (i<rows){
                model.removeRow(i);
            }
        } catch(Exception e) {
            System.out.println(e);
        }
        
        try {
            JTableHeader header= Tabla.getTableHeader();
            TableColumnModel colMod = header.getColumnModel();
            TableColumn tabCol = colMod.getColumn(3);
            tabCol.setHeaderValue("CPU");
            header.repaint();

            tabCol = colMod.getColumn(4);
            tabCol.setHeaderValue("GPU");
            header.repaint();
        } catch (Exception e){
            System.out.println(e);
        }
        
        
        Connection conn = null;
        String sql = "SELECT * from inventario WHERE tipo=?";
        try {
            conn = DriverManager.getConnection(CONN_STRING, USERNAME, PASSWORD);
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, "computadora");
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                String nombre = rs.getString("nombre");
                String marca = rs.getString("marca");
                int precio = rs.getInt("precio");
                String info1 = rs.getString("info1");
                String info2 = rs.getString("info2");
              
                model.addRow(new Object[]{nombre, marca, precio, info1, info2});
            }
        } catch (SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_compuActionPerformed

    private void tvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)Tabla.getModel();
        try {
            int i = 0;
            int rows = Tabla.getRowCount();
            while (i<rows){
                model.removeRow(i);
            }
        } catch (Exception e){
            System.out.println(e);
        }
        
        
        try {
            JTableHeader header= Tabla.getTableHeader();
            TableColumnModel colMod = header.getColumnModel();
            TableColumn tabCol = colMod.getColumn(3);
            tabCol.setHeaderValue("Taza de Refresco");
            header.repaint();

            tabCol = colMod.getColumn(4);
            tabCol.setHeaderValue("Resolucion");
            header.repaint();
        } catch (Exception e){
            System.out.println(e);
        }
        
        
        Connection conn = null;
        String sql = "SELECT * from inventario WHERE tipo=?";
        try {
            conn = DriverManager.getConnection(CONN_STRING, USERNAME, PASSWORD);
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, "Tv");
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                String nombre = rs.getString("nombre");
                String marca = rs.getString("marca");
                int precio = rs.getInt("precio");
                String info1 = rs.getString("info1");
                String info2 = rs.getString("info2");
                
                model.addRow(new Object[]{nombre, marca, precio, info1, info2});
            }
        } catch (SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_tvActionPerformed

    private void telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)Tabla.getModel();
        try {
            int i = 0;
            int rows = Tabla.getRowCount();
            while (i<rows){
                model.removeRow(i);
            }
        } catch (Exception e){
            System.out.println(e);
        }
        
        try {
            JTableHeader header= Tabla.getTableHeader();
            TableColumnModel colMod = header.getColumnModel();
            TableColumn tabCol = colMod.getColumn(3);
            tabCol.setHeaderValue("OS");
            header.repaint();

            tabCol = colMod.getColumn(4);
            tabCol.setHeaderValue("Tamaño");
            header.repaint();
        } catch (Exception e){
            System.out.println(e);
        }
        
        Connection conn = null;
        String sql = "SELECT * from inventario WHERE tipo=?";
        try {
            conn = DriverManager.getConnection(CONN_STRING, USERNAME, PASSWORD);
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, "telefono");
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                String nombre = rs.getString("nombre");
                String marca = rs.getString("marca");
                int precio = rs.getInt("precio");
                String info1 = rs.getString("info1");
                String info2 = rs.getString("info2");
                
                model.addRow(new Object[]{nombre, marca, precio, info1, info2});
            }
        } catch (SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_telActionPerformed

    private void saldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saldoActionPerformed

    private void comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarActionPerformed
        // TODO add your handling code here:     
        if (confirm.isSelected()){
            int precio = Integer.parseInt(priceConf.getText());
            String saldoFinal = Integer.toString(Integer.parseInt(saldo.getText()) - precio);
            saldo.setText(saldoFinal);
            JOptionPane.showMessageDialog(null, "Compra efectuada exitosamente. ¡Gracias!");
            
            Connection conn = null;
            String sql = "UPDATE users SET saldo=? WHERE correo=?";
            try {
                conn = DriverManager.getConnection(CONN_STRING, USERNAME, PASSWORD);
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setInt(1, Integer.parseInt(saldoFinal));
                ps.setString(2, (CustomId.getText()));
                ps.execute();
                ps.close();
                ps=null;
                conn.close();
            } catch (SQLException e) {
                System.out.println(e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Confirmacion no ha sido seleccionada.");
        }
    }//GEN-LAST:event_comprarActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)Tabla.getModel();
        int SelectedRowIndex = Tabla.getSelectedRow();       
        priceConf.setText(model.getValueAt(SelectedRowIndex, 2).toString());
        info1.setText(model.getValueAt(SelectedRowIndex, 0).toString());
        info2.setText(model.getValueAt(SelectedRowIndex, 1).toString());
    }//GEN-LAST:event_TablaMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String email = CustomId.getText();
        Connection conn = null;
        try {
            conn = DriverManager.getConnection(CONN_STRING, USERNAME, PASSWORD);
            String sql = "SELECT * FROM users WHERE correo = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, email);
            ps.execute();
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                saldo.setText(Integer.toString(rs.getInt("saldo")));
                if (rs.getInt("saldo") <= 0){
                    JOptionPane.showMessageDialog(null, "Saldo igual o menor a cero.");
                    Dinero.setText("Deuda");
                } else {
                    Dinero.setText("Saldo");
                }
            }
            ps.close();
            ps=null;
            conn.close();
        } catch(SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmActionPerformed

    private void infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoActionPerformed
        // TODO add your handling code here:
        ArrayList<String> list = new ArrayList();
        list.add(info1.getText());
        list.add(info2.getText());
        list.add(priceConf.getText());
        
        for (int i = 0; i<list.size(); i++){
            Area.append(list.get(i));
            Area.append("\n");
        }
    }//GEN-LAST:event_infoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Area;
    private javax.swing.JLabel CustomId;
    private javax.swing.JLabel Dinero;
    private javax.swing.JTable Tabla;
    private javax.swing.JButton comprar;
    private javax.swing.JButton compu;
    private javax.swing.JCheckBox confirm;
    private javax.swing.JButton info;
    private javax.swing.JTextField info1;
    private javax.swing.JTextField info2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField priceConf;
    private javax.swing.JTextField saldo;
    private javax.swing.JButton tel;
    private javax.swing.JButton tv;
    // End of variables declaration//GEN-END:variables
}
